#line 1 "lex.yy.c"

#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[260] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  109,  107,
      105,  106,   90,   15,    6,   86,   91,   24,   97,   98,
       83,   81,   96,   82,   94,   85,   12,   12,  103,   95,
       88,   87,   89,  104,  101,  102,   84,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,   99,
       92,  100,   93,    4,    3,    4,   17,   20,   16,  108,
       26,   29,   25,  108,  105,   73,    0,   14,   13,    0,
        6,   71,   76,    0,   23,   21,    0,   78,   67,   79,
       68,   80,    8,    0,    0,   70,    7,   12,    0,    0,
        0,   65,   74,   72,   75,   66,  104,   69,   64,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   46,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,   77,    2,   17,   16,   19,   18,   26,
       25,   28,   27,   14,    0,   22,    0,   23,    0,    1,
        5,    7,    0,    9,   10,   11,   63,  104,  104,  104,
      104,  104,  104,  104,  104,   60,  104,  104,  104,   48,
       34,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,    0,    8,    5,    0,    0,    7,
      104,   39,  104,   53,   37,  104,  104,   47,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104,  104,  104,   61,  104,  104,   38,  104,    0,    7,
       59,  104,   55,  104,  104,  104,   62,   36,  104,  104,
      104,  104,  104,  104,   35,  104,  104,  104,  104,  104,
      104,   51,   49,  104,  104,  104,   44,  104,  104,  104,
       30,   50,   57,   42,   58,   45,   41,   52,  104,   40,
      104,   54,   31,   32,   33,  104,   56,   43,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   23,   25,   26,   27,   28,   29,
       30,   31,    1,    1,   32,   32,   32,   32,   33,   32,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   34,   49,   50,   34,   51,
       52,   53,   34,   54,   55,   56,   57,   58,   59,   60,
       34,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    5,    1,    5,    6,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1,
        1,    8,    9,   10,    1,   11,    1,    1,   10,    8,
       12,    8,    8,    9,    8,   10,   10,   10,   10,   10,
       10,   13,   10,   10,   10,   10,   10,   10,   10,   13,
       10,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[280] =
    {   0,
        0,    0,   63,   64,   65,   66,   69,   70,  533,  534,
      530,  534,  501,   77,    0,  500,  521,   74,  534,  534,
      534,   61,  534,   66,   96,   73,   71,   83,  534,  534,
       59,  498,   62,    0,  534,  534,   56,   82,   85,  483,
       78,   90,   53,  482,   97,  471,  473,  471,  475,  534,
      458,  534,  534,  534,  534,  503,  514,  534,  534,  515,
      508,  534,  534,  513,  513,  534,  136,  511,  534,  510,
        0,  534,  534,  124,  509,  534,  508,  534,  534,  534,
      534,  534,   51,  498,  492,  534,   67,    0,   89,  128,
        0,  534,  477,  534,  534,  534,    0,  534,  534,  461,

      454,  461,  449,  463,  451,  456,  445,  456,  442,  447,
      444,  441,    0,  438,  101,  441,  109,  119,  444,  434,
      106,  442,  441,  534,  534,  483,  534,  534,  534,  478,
      534,  534,  534,  534,  155,  534,  483,  534,  150,  534,
        0,  133,  154,  156,  160,    0,  534,  437,  434,  443,
      438,  427,  424,  439,  434,    0,  433,  421,  435,    0,
      168,  430,  416,  418,  420,  426,  413,  411,  411,  422,
      417,  416,  420,  412,  176,  185,    0,  173,  194,  203,
      410,  416,  410,    0,    0,  410,  400,    0,  402,  411,
      398,  429,  432,  429,  411,  409,  394,  391,  402,  393,

      396,  401,  400,    0,  395,  390,    0,  394,  212,  221,
        0,  395,    0,  371,  369,  365,    0,    0,  376,  371,
      368,  327,  321,  317,    0,  313,  306,  300,  282,  284,
      279,    0,    0,  278,  271,  245,    0,  134,  129,  120,
        0,    0,    0,    0,    0,    0,    0,    0,  127,    0,
      124,    0,    0,    0,    0,   66,    0,    0,  534,  247,
      260,  273,  286,  299,  312,  320,  327,  340,  353,  366,
      379,  392,  399,  402,  405,  413,  420,  429,  432
    } ;

static const flex_int16_t yy_def[280] =
    {   0,
      259,    1,  260,  260,  261,  261,  262,  262,  259,  259,
      259,  259,  259,  263,  264,  259,  259,  265,  259,  259,
      259,  259,  259,  259,  259,  259,  266,  266,  259,  259,
      259,  259,  259,  267,  259,  259,  259,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  259,
      259,  259,  259,  259,  259,  259,  268,  259,  259,  269,
      270,  259,  259,  271,  259,  259,  263,  259,  259,  263,
      264,  259,  259,  272,  259,  259,  265,  259,  259,  259,
      259,  259,  273,  259,  259,  259,  274,   28,  259,  259,
      275,  259,  259,  259,  259,  259,  267,  259,  259,  267,

      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  259,  259,  268,  259,  259,  259,  270,
      259,  259,  259,  259,  272,  259,  272,  259,  276,  259,
      277,  274,  278,  259,  259,  275,  259,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  259,  259,  277,  279,  259,  259,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  267,  267,  267,  267,  259,  259,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,    0,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259
    } ;

static const flex_int16_t yy_nxt[600] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   28,
       28,   28,   28,   28,   28,   28,   29,   30,   31,   32,
       33,   34,   34,   34,   35,   10,   36,   37,   34,   34,
       38,   39,   40,   41,   42,   34,   34,   43,   34,   34,
       34,   34,   34,   44,   45,   46,   47,   48,   49,   34,
       34,   50,   51,   52,   53,   55,   55,   58,   58,   59,
       59,   62,   62,   78,   56,   56,   75,   63,   63,   68,
       80,   69,   76,  139,   84,   98,   87,   92,   93,   85,
       79,   95,   96,   99,  139,   81,   82,  113,   87,  143,

       60,   60,   86,  114,   64,   64,  144,  144,  258,   77,
      143,   89,   70,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   90,  259,  103,  100,   75,  107,  108,  110,
       91,  104,  136,  101,  259,  102,  105,  109,   68,  111,
       69,  112,  259,  116,  117,  145,  145,  145,  145,  145,
      145,  145,  118,  162,  165,  119,  163,   75,  167,  137,
      171,  172,  175,  259,  175,  178,  179,  257,  179,  166,
      256,   70,  168,  144,  144,  255,  178,  145,  145,  145,
      145,  145,  145,  145,  254,  209,  192,  209,  193,  253,
      137,  194,  195,  176,  176,  176,  176,  176,  176,  176,

      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   71,

      252,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   88,   88,  251,  250,  249,
      248,   88,   88,   97,   97,   97,   97,  247,   97,   97,
      126,  246,  126,  126,  126,  126,  126,  126,  126,  126,
      245,  126,  126,  128,  128,  244,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  130,  243,  130,  130,
      130,  130,  130,  130,  130,  130,  242,  130,  130,  132,
      132,  132,  241,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  135,  135,  135,  135,  135,  135,  135,  135,

      135,  135,  135,  135,  135,   83,  240,   83,  142,  239,
      142,  146,  146,  146,  238,  237,  146,  176,  236,  176,
      177,  235,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  180,  234,  180,  210,  233,  210,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  259,  131,  127,  174,  173,
      170,  169,  164,  161,  160,  159,  158,  157,  156,  155,

      154,  153,  152,  151,  150,  149,  148,  147,  141,  140,
      259,  138,  259,  134,   65,  133,  131,  129,  127,  125,
      124,  123,  122,  121,  120,  115,  106,   94,   73,   72,
       66,   65,  259,    9,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259

    } ;

static const flex_int16_t yy_chk[600] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,    5,
        6,    7,    8,   22,    3,    4,   18,    7,    8,   14,
       24,   14,   18,   83,   26,   37,   27,   31,   31,   26,
       22,   33,   33,   37,   83,   24,   24,   43,   28,   87,

        5,    6,   26,   43,    7,    8,   89,   89,  256,   18,
       87,   27,   14,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   27,   28,   39,   38,   74,   41,   41,   42,
       27,   39,   74,   38,   28,   38,   39,   41,   67,   42,
       67,   42,   28,   45,   45,   90,   90,   90,   90,   90,
       90,   90,   45,  115,  117,   45,  115,  135,  118,   74,
      121,  121,  139,  135,  139,  142,  143,  251,  143,  117,
      249,   67,  118,  144,  144,  240,  142,  145,  145,  145,
      145,  145,  145,  145,  239,  178,  161,  178,  161,  238,
      135,  161,  161,  175,  175,  175,  175,  175,  175,  175,

      175,  175,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  264,

      236,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  266,  266,  235,  234,  231,
      230,  266,  266,  267,  267,  267,  267,  229,  267,  267,
      268,  228,  268,  268,  268,  268,  268,  268,  268,  268,
      227,  268,  268,  269,  269,  226,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  270,  224,  270,  270,
      270,  270,  270,  270,  270,  270,  223,  270,  270,  271,
      271,  271,  222,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  272,  272,  272,  272,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  273,  221,  273,  274,  220,
      274,  275,  275,  275,  219,  216,  275,  276,  215,  276,
      277,  214,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  278,  212,  278,  279,  208,  279,  206,
      205,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  187,  186,  183,  182,
      181,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  159,  158,  157,  155,  154,  153,
      152,  151,  150,  149,  148,  137,  130,  126,  123,  122,
      120,  119,  116,  114,  112,  111,  110,  109,  108,  107,

      106,  105,  104,  103,  102,  101,  100,   93,   85,   84,
       77,   75,   70,   68,   65,   64,   61,   60,   57,   56,
       51,   49,   48,   47,   46,   44,   40,   32,   17,   16,
       13,   11,    9,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[109] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 
    1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "kernalex.l"
#line 2 "kernalex.l"
#include <stdio.h>
#include <string.h>
#include "tokens.h"

int line_num = 1;
int column_num = 1;
int string_start_col = 0;
int string_start_line = 0;
int char_start_col = 0;
int char_start_line = 0;
int comment_start_col = 0;
int comment_start_line = 0;

int token_start_col = 0;

void process_token(const char *text, int save_start) {
    if (save_start) {
        token_start_col = column_num;
    }
    
    for (int i = 0; text[i] != '\0'; i++) {
        if (text[i] == '\n') {
            line_num++;
            column_num = 1;
        } else {
            column_num++;
        }
    }
}

#line 726 "lex.yy.c"

#line 728 "lex.yy.c"

#define INITIAL 0
#define COMMENT_ML 1
#define STRING_STATE 2
#define CHAR_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 41 "kernalex.l"


#line 951 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 534 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 43 "kernalex.l"
{ 
    token_start_col = column_num;
    column_num += 3;
    comment_start_line = line_num;
    comment_start_col = token_start_col;
    BEGIN(COMMENT_ML); 
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "kernalex.l"
{ process_token(yytext, 0); BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "kernalex.l"
{ line_num++; column_num = 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "kernalex.l"
{ column_num++; }
	YY_BREAK
case YY_STATE_EOF(COMMENT_ML):
#line 53 "kernalex.l"
{
    printf("[ERROR: Line %d, Col %d: Unterminated multi-line comment]\n", 
           comment_start_line, comment_start_col);
    return 0;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "kernalex.l"
{ process_token(yytext, 1); printf("[DOC_COMMENT: %s]\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "kernalex.l"
{ process_token(yytext, 1); printf("[COMMENT: %s]\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "kernalex.l"
{ process_token(yytext, 1); printf("[FLOAT_LIT: %s] (Token #%d)\n", yytext, TOK_FLOAT_LIT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "kernalex.l"
{ process_token(yytext, 1); printf("[FLOAT_LIT: %s] (Token #%d)\n", yytext, TOK_FLOAT_LIT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "kernalex.l"
{ process_token(yytext, 1); printf("[INTEGER: %s] (Token #%d)\n", yytext, TOK_INTEGER); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "kernalex.l"
{ process_token(yytext, 1); printf("[INTEGER: %s] (Token #%d)\n", yytext, TOK_INTEGER); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "kernalex.l"
{ process_token(yytext, 1); printf("[INTEGER: %s] (Token #%d)\n", yytext, TOK_INTEGER); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "kernalex.l"
{ process_token(yytext, 1); printf("[INTEGER: %s] (Token #%d)\n", yytext, TOK_INTEGER); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "kernalex.l"
{ 
    process_token(yytext, 1); 
    printf("[STRING_LIT: %s] (Token #%d)\n", yytext, TOK_STRING_LIT); 
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 76 "kernalex.l"
{
    string_start_line = line_num;
    string_start_col = column_num;  // Position of the opening quote
    if (yytext[yyleng-1] == '\n') {
        line_num++;
        column_num = 1;
    } else {
        process_token(yytext, 0);
    }
    printf("[ERROR: Line %d, Col %d: Unterminated string literal]\n", 
           string_start_line, string_start_col);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "kernalex.l"
{
    token_start_col = column_num;
    string_start_line = line_num;
    string_start_col = token_start_col;
    column_num++;
    BEGIN(STRING_STATE);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "kernalex.l"
{
    process_token(yytext, 0);
    printf("[STRING_LIT: \"%s] (Token #%d)\n", yytext, TOK_STRING_LIT);
    BEGIN(INITIAL);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "kernalex.l"
{
    for (int i = 0; yytext[i] != '\0'; i++) {
        column_num++;
    }
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 109 "kernalex.l"
{
    line_num++;
    column_num = 1;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "kernalex.l"
{
    column_num += 2;  // '\' + next char
}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 118 "kernalex.l"
{
    line_num++;
    column_num = 1;
    printf("[ERROR: Line %d, Col %d: Unterminated string literal]\n", 
           string_start_line, string_start_col);
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 126 "kernalex.l"
{
    printf("[ERROR: Line %d, Col %d: Unterminated string literal at EOF]\n", 
           string_start_line, string_start_col);
    return 0;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 132 "kernalex.l"
{
    token_start_col = column_num;
    column_num += 2;
    printf("[ERROR: Line %d, Col %d: Empty character literal]\n", line_num, token_start_col);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 138 "kernalex.l"
{
    token_start_col = column_num;
    char_start_col = token_start_col;
    process_token(yytext, 0);
    
    if (yyleng == 4 && yytext[1] == '\\') {
        printf("[CHAR_LIT: %s] (Token #%d)\n", yytext, TOK_CHAR_LIT);
    } else if (yyleng == 3) {
        printf("[CHAR_LIT: %s] (Token #%d)\n", yytext, TOK_CHAR_LIT);
    } else if (yyleng > 4) {
        printf("[ERROR: Line %d, Col %d: Multiple characters in character literal]\n", 
               line_num, char_start_col);
    }
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 153 "kernalex.l"
{
    char_start_line = line_num;
    char_start_col = column_num;
    if (yytext[yyleng-1] == '\n') {
        line_num++;
        column_num = 1;
    } else {
        process_token(yytext, 0);
    }
    printf("[ERROR: Line %d, Col %d: Unterminated character literal]\n", 
           char_start_line, char_start_col);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 166 "kernalex.l"
{
    token_start_col = column_num;
    char_start_line = line_num;
    char_start_col = token_start_col;
    column_num++;
    BEGIN(CHAR_STATE);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 174 "kernalex.l"
{
    process_token(yytext, 0);
    printf("[CHAR_LIT: '%s] (Token #%d)\n", yytext, TOK_CHAR_LIT);
    BEGIN(INITIAL);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 180 "kernalex.l"
{
    for (int i = 0; yytext[i] != '\0'; i++) {
        column_num++;
    }
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 186 "kernalex.l"
{
    line_num++;
    column_num = 1;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 191 "kernalex.l"
{
    column_num += 2;
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 195 "kernalex.l"
{
    line_num++;
    column_num = 1;
    printf("[ERROR: Line %d, Col %d: Unterminated character literal]\n", 
           char_start_line, char_start_col);
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(CHAR_STATE):
#line 203 "kernalex.l"
{
    printf("[ERROR: Line %d, Col %d: Unterminated character literal at EOF]\n", 
           char_start_line, char_start_col);
    return 0;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 209 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_INT8_T); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 210 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_INT16_T); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 211 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_INT32_T); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 212 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_INT64_T); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 213 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_INT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 214 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_SHORT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 215 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_FLOAT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 216 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_CHAR); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 217 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_VOID); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 218 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_BOOL); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 219 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_BOOLEAN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 220 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_STRUCT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 221 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_SIGNED); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 222 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_UNSIGNED); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 223 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_EXTERN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 224 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_STATIC); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 225 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_IF); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 226 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_ELSE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 227 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_FOR); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 228 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_WHILE); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 229 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_REPEAT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 230 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_UNTIL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 231 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_SWITCH); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 232 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_CASE); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 233 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_DEFAULT); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 234 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_BREAK); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 235 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_CONTINUE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 236 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_RETURN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 237 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_SIZEOF); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 238 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_BEGIN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 239 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_END); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 240 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_TRUE); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 241 "kernalex.l"
{ process_token(yytext, 1); printf("[KEYWORD: %s] (Token #%d)\n", yytext, TOK_FALSE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 243 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_SPACESHIP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 244 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_XOR); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 245 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_LSHIFT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 246 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_RSHIFT); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 247 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_PLUSEQ); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 248 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_MINUSEQ); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 249 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_MULTEQ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 250 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_DIVEQ); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 251 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_MODEQ); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 252 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_EQ); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 253 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_NE); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 254 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_LE); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 255 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_GE); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_AND); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_OR); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 258 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_INC); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 259 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_DEC); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 260 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_ARROW); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 262 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_PLUS); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 263 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_MINUS); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 264 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_STAR); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 265 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_MULT); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 266 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_DIV); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 267 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_MOD); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 268 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_ASSIGN); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 269 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_LT); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 270 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_GT); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 271 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_NOT); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 272 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_AMP); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 273 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_BITOR); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 274 "kernalex.l"
{ process_token(yytext, 1); printf("[OPERATOR: %s] (Token #%d)\n", yytext, TOK_BITNOT); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 276 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_DOT); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 277 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_SEMICOLON); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 278 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_COMMA); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 279 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_LPAREN); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 280 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_RPAREN); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 281 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_LBRACE); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 282 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_RBRACE); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 283 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_LBRACKET); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 284 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_RBRACKET); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 285 "kernalex.l"
{ process_token(yytext, 1); printf("[PUNCTUATION: %s] (Token #%d)\n", yytext, TOK_COLON); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 287 "kernalex.l"
{
    token_start_col = column_num;
    process_token(yytext, 0);
    if (yyleng <= 255) {
        printf("[IDENTIFIER: %s] (Token #%d)\n", yytext, TOK_IDENTIFIER);
    } else {
        printf("[ERROR: Line %d, Col %d: Identifier too long (max 255)]\n", 
               line_num, token_start_col);
    }
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 298 "kernalex.l"
{ for (int i = 0; yytext[i] != '\0'; i++) { column_num++; } }
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 300 "kernalex.l"
{ line_num++; column_num = 1; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 302 "kernalex.l"
{ 
    int err_col = column_num;
    printf("[ERROR: Line %d, Col %d: Unknown/Invalid character '%c' (ASCII %d)]\n", 
           line_num, err_col, yytext[0], (unsigned char)yytext[0]); 
    column_num++;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 309 "kernalex.l"
{ return 0; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 311 "kernalex.l"
ECHO;
	YY_BREAK
#line 1714 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 259);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 311 "kernalex.l"


int main(int argc, char *argv[]){
    if(argc > 1){
        yyin = fopen(argv[1], "r");
        if(!yyin){
            fprintf(stderr, "Error: Could not open file %s\n", argv[1]);
            return 1;
        }
    }
    
    yylex();
    
    if(argc > 1){
        fclose(yyin);
    }
    
    return 0;
}

